### Add a new User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "userName": "jimmy",
    "email": "jimmy@gmail.com",
    "password": "jimmy"
}
### Login the existing User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "jimmy@gmail.com",
    "password": "jimmy"
}

### Delete the existing the User through userName
DELETE http://localhost:5000/api/users/delete/jimmy

### Add method to add user data using userName
POST http://localhost:5000/api/userdatas/add
Content-Type: application/json

{
    "userName": "jimmy",
    "bookmarks": ["PL Score", "World News"],
    "preferences": {
        "theme": "light",
        "language": "nep"
    }
}

### Get the User Data through userName
GET http://localhost:5000/api/userdatas/userName/jimmy
### Update the User Data through userName
PUT http://localhost:5000/api/userdatas/update/jimmy
Content-Type: application/json

{
    "bookmarks": ["wildfire in USA", "Protests"],
    "preferences": {
        "theme": "light",
        "language": "fr"
    }
}
### Delete the User Data through userName
DELETE http://localhost:5000/api/userdatas/delete/jimmy

