### Add a new User
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "userName": "swfdns",
    "email": "bsdfgmail.com",
    "password": "BFdasfh344" 
}
### Login the existing User
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "abhi@gmail.com",
    "password": "Hero223"
}

### Delete the existing the User
DELETE http://localhost:5000/api/users/delete/adam


### Add the User Data
POST http://localhost:5000/api/user-data/add
Content-Type: application/json

{
    "userId": "67df45e4a890c0560ddd8a78",
    "bookmarks": ["C1", "D3"],
    "preferences": {"theme": "light", "language": "hin"}
}

### Get the User Data
GET http://localhost:5000/api/user-data/userId/67df45e4a890c0560ddd8a78

### Update the User Data
PUT http://localhost:5000/api/user-data/update/67df45e4a890c0560ddd8a78
Content-Type: application/json

{
    "bookmarks": ["abc", "new-bookmark"],
    "preferences": {
        "theme": "light",
        "language": "fr"
    }
}
### Delete the User Data
DELETE http://localhost:5000/api/user-data/delete

